Implement simplified credentials in YDB SDK
yandex-cloud/ydb-nodejs-sdk pull request #80
Opened 2021-07-23 07:21 UTC by rrewll

2021-07-28 11:11 UTC, tsufiev requested changes
Очень хочется не ломать (по возможности) текущую сигнатуру конструктора.

2021-07-28 11:11 UTC, tsufiev commented on src/driver.ts
> +    constructor(config: DriverConfig) {
Можем ли мы сделать constructor overload, поддержав и старый способ передачи параметров и новый? В таком случае, существующим клиентам не придется срочно переписывать свой код для перехода на следующую версию. А отказ от нынешнего способа инициализации конструктора мы запланируем на следующий мажорный релиз.

2021-07-28 11:11 UTC, tsufiev commented on src/driver.ts
> +    entryPoint?: string,
А зачем здесь entryPoint и database, если ты их всегда получаешь из connectionString?

2021-07-28 11:12 UTC, tsufiev commented
Кроме того, надо будет еще обновить README.

2021-07-28 12:31 UTC, rrewll commented on src/parse-env-vars.ts
> +    if (process.env.YDB_ANONYMOUS_CREDENTIALS === '1') {
Исправил

2021-07-28 12:32 UTC, rrewll commented on examples/scan-query/index.ts
> +    const database = driver.database;
А это же поле не менялось? Т.е. как было раньше публичное поле database, так и осталось.

2021-07-28 12:33 UTC, rrewll commented on src/driver.ts
> +    constructor(config: DriverConfig) {
Поддержал полностью обратную совместимость со старым кодом

2021-07-28 13:13 UTC, tsufiev commented on examples/scan-query/index.ts
> +    const database = driver.database;
Я имею в виду локальное имя переменной в `run`.

2021-07-28 13:13 UTC, tsufiev commented on examples/utils.ts
> +    (logger: Logger, endpoint: string): Promise<void>;
Тогда оно ведь должно называться не endpoint, а connectionString - согласно новому соглашению.

2021-07-28 13:33 UTC, rrewll commented on examples/scan-query/index.ts
> +    const database = driver.database;
Переименовал

2021-07-28 13:35 UTC, rrewll commented on src/driver.ts
> +    entryPoint?: string,
Подразумевается, что способ через entryPoint/database остаётся.
Так реализовано в Python SDK и, я так понимаю, будет реализовано во всех остальных.

2021-07-28 13:40 UTC, rrewll commented on examples/utils.ts
> +    (logger: Logger, endpoint: string): Promise<void>;
Переименовал

2021-07-29 12:39 UTC, tsufiev commented on README.md
> +export YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS= # here comes your token from `yc iam create-token`
YDB_ACCESS_TOKEN_CREDENTIALS

2021-07-29 12:39 UTC, tsufiev commented on README.md
> +New credential variables:
New credential variables -> For the typical cases of using these variables, see below.

2021-07-29 12:39 UTC, tsufiev commented on examples/utils.ts
> +        db = args.db as string;
```suggestion
        endpoint = endpointParam;
        db = dbParam;
```

2021-07-29 12:39 UTC, tsufiev commented on src/parse-env-vars.ts
> +    function getOldSslCredentials() {
Отличная идея! Сохраняем поведение SSL-сертификатов со старыми переменными таким же, каким оно было до этого.

2021-07-29 12:51 UTC, rrewll commented on src/driver.ts
> +    entryPoint?: string,
Уже неактуально

2021-07-29 12:51 UTC, rrewll commented on README.md
> +export YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS= # here comes your token from `yc iam create-token`
Поменял

2021-07-29 12:52 UTC, rrewll commented on README.md
> +export YDB_ANONYMOUS_CREDENTIALS=1 # credentials are disabled
Поменял

2021-07-29 12:52 UTC, rrewll commented on README.md
> +export YDB_METADATA_CREDENTIALS=1 # here initializes local metadata service
Поменял

2021-07-29 12:52 UTC, rrewll commented on README.md
> +New credential variables:
Поменял

2021-07-29 12:52 UTC, rrewll commented on examples/utils.ts
> +        throw new Error('One of --connection-string <connection_string> or --db <database> --endpoint <endpoint> arguments are required');
Поменял

2021-07-29 12:52 UTC, rrewll commented on src/parse-env-vars.ts
> +        logger.debug('deprecated YDB_TOKEN env var found, using TokenAuthService.');
Поменял на warn

2021-07-29 12:54 UTC, rrewll commented on README.md
> +Deprecated credential variables (will be removed in the next major release):
Добавил в конец раздела:
### Deprecated variables
These variables will be removed in the next major release:
...

2021-07-30 09:49 UTC, tsufiev approved these changes

2021-07-30 11:29 UTC, merged